# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Forums
    url: https://undeadservers.org
  - name: Panel
    url: https://undead-panel.com
status-website:
  # Custom stuff
  publish: true
  apiBaseUrl: ${{ secrets.GH_PAT }}
  cname: status.uundeadservers,irg
  
  theme: night

  logoUrl: https://undeadservers.org/Themes/lagusta_20rc5/images/custom/logo.png
  name: Undead Servers
  introTitle: "**Downtime & Status**"
  introMessage: This is the page where you can view all downtime/status for our services.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
