# Change these first
owner: reformscripts # Your GitHub organization or username, where this repository lives
repo: undead-uptime # The name of this repository

i18n:
    footer: ""
sites:
  - name: Forums
    url: https://undeadservers.org
  - name: Donation Store
    url: https://store.undeadservers.org
  - name: Pterodactyl Panel
    check: "tcp-ping"
    url: https://undead-panel.com
    port: 8080
  - name: Pterodactyl sFTP
    check: "tcp-ping"
    url: https://undead-panel.com
    port: 2022
  - name: Pterodactyl MySQL
    check: "tcp-ping"
    url: https://undead-panel.com
    port: 3306
  - name: Classic DarkRP
    check: "tcp-ping"
    url: https://undead-panel.com
    port: 27016
status-website:
  # Custom stuff
  cname: status.undeadservers.org
  
  theme: night

  logoUrl: https://undeadservers.org/Themes/lagusta_20rc5/images/custom/logo.png
  name: Undead Servers
  introTitle: "**Downtime & Status**"
  introMessage: This is the page where you can view all downtime/status for our services.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
