# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Forums
    url: https://undeadservers.org
  - name: Panel
    url: https://undead-panel.com
status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.undeadservers.org
  # baseUrl: /your-repo-name
  logoUrl: https://undeadservers.org/Themes/lagusta_20rc5/images/custom/logo.png
  name: Undead Servers
  introTitle: "**Downtime & Status**"
  introMessage: This is the page where you can view all downtime/status for our services.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
